- hosts: masters, nodes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: create the kubernetes user
      user: name="{{k8s_user}}" append=yes state=present createhome=yes shell=/bin/bash

    - name: allow kubernetes user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '"{{k8s_user}}" ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user="{{k8s_user}}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
