- hosts: masters, nodes
  become: yes
  tasks:
   - name: Install aptitude using apt
     apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

   - name: Install required system packages
     apt: name={{ item }} state=latest update_cache=yes
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

   - name: Add Docker GPG apt Key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       state: present

   - name: install Docker
     apt:
       name: "{{item}}"
       state: present
       update_cache: yes
     loop:
       - docker-ce
       - docker-ce-cli
       - containerd.io

   - name: Install Docker Module for Python
     pip:
       name: docker

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   #Kubelet will not start if the system has swap enabled, so we are disabling swap using the below code
   - name: Remove swapfile from /etc/fstab
     mount:
       name: "{{ item }}"
       fstype: swap
       state: absent
     with_items:
       - swap
       - none

   - name: Disable swap
     command: swapoff -a
     when: ansible_swaptotal_mb > 0

   #Installing kubelet, kubeadm and kubectl using the below code. 
   - name: Install Kubernetes binaries
     apt: 
       name: "{{ packages }}"
       state: present
       update_cache: yes
     vars:
       packages:
         - kubelet
         - kubeadm

   - name: Restart kubelet
     service:
       name: kubelet
       daemon_reload: yes
       state: restarted

- hosts: masters
  become: yes
  tasks:
   - name: install kubectl=1.20.4-00
     apt:
       name: kubectl
       state: present
       force: yes
